// Code generated by protoc-gen-go-http. DO NOT EDIT.
// versions:
// - protoc-gen-go-http v2.8.3
// - protoc             v3.11.4
// source: api/server/server_http.proto

package server

import (
	context "context"
	http "github.com/go-kratos/kratos/v2/transport/http"
	binding "github.com/go-kratos/kratos/v2/transport/http/binding"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the kratos package it is being compiled against.
var _ = new(context.Context)
var _ = binding.EncodeURL

const _ = http.SupportPackageIsVersion1

const OperationServerCreateServer = "/api.server.Server/CreateServer"

type ServerHTTPServer interface {
	CreateServer(context.Context, *CreateServerRequest) (*CreateServerReply, error)
}

func RegisterServerHTTPServer(s *http.Server, srv ServerHTTPServer) {
	r := s.Route("/")
	r.POST("/example/createServer", _Server_CreateServer0_HTTP_Handler(srv))
}

func _Server_CreateServer0_HTTP_Handler(srv ServerHTTPServer) func(ctx http.Context) error {
	return func(ctx http.Context) error {
		var in CreateServerRequest
		if err := ctx.Bind(&in); err != nil {
			return err
		}
		if err := ctx.BindQuery(&in); err != nil {
			return err
		}
		http.SetOperation(ctx, OperationServerCreateServer)
		h := ctx.Middleware(func(ctx context.Context, req interface{}) (interface{}, error) {
			return srv.CreateServer(ctx, req.(*CreateServerRequest))
		})
		out, err := h(ctx, &in)
		if err != nil {
			return err
		}
		reply := out.(*CreateServerReply)
		return ctx.Result(200, reply)
	}
}

type ServerHTTPClient interface {
	CreateServer(ctx context.Context, req *CreateServerRequest, opts ...http.CallOption) (rsp *CreateServerReply, err error)
}

type ServerHTTPClientImpl struct {
	cc *http.Client
}

func NewServerHTTPClient(client *http.Client) ServerHTTPClient {
	return &ServerHTTPClientImpl{client}
}

func (c *ServerHTTPClientImpl) CreateServer(ctx context.Context, in *CreateServerRequest, opts ...http.CallOption) (*CreateServerReply, error) {
	var out CreateServerReply
	pattern := "/example/createServer"
	path := binding.EncodeURL(pattern, in, false)
	opts = append(opts, http.Operation(OperationServerCreateServer))
	opts = append(opts, http.PathTemplate(pattern))
	err := c.cc.Invoke(ctx, "POST", path, in, &out, opts...)
	if err != nil {
		return nil, err
	}
	return &out, nil
}
