// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"kratos_one/cursor_wire/internal/api"
	"kratos_one/cursor_wire/internal/config"
	"kratos_one/cursor_wire/internal/repository"
	"kratos_one/cursor_wire/internal/service"
)

// Injectors from wire.go:

// InitializeAPI 是一个Wire函数，用于初始化API
// 通过使用wire.Build，我们告诉Wire如何构建依赖关系图
func InitializeAPI() (*api.API, error) {
	configConfig := config.NewConfig()
	database, err := repository.NewDatabase(configConfig)
	if err != nil {
		return nil, err
	}
	repositoryRepository := repository.NewRepository(configConfig, database)
	serviceService := service.NewService(repositoryRepository)
	apiAPI := api.NewAPI(configConfig, serviceService)
	return apiAPI, nil
}
