// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

// Injectors from wire.go:

// InitMission 注入器，用于创建并注入依赖
func InitMission(name string) Mission {
	player := NewPlayer(name)
	monster := NewMonster()
	mission := NewMission(player, monster)
	return mission
}
